info:
  title: ABCall
  description: ''
  version: 1.0.0
tags: []
paths:
  /v1/invoices/{id}:
    get:
      summary: Get invoice
      deprecated: false
      description: ''
      operationId: invoicesGet
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          format: uuid
          type: string
          x-example: '{% faker datatype.uuid %}'
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties: {}
      security:
        - tokenAdmin: []
      produces:
        - application/json
      x-google-backend:
        address: "${invoice_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
  /v1/health/invoice:
    get:
      summary: Health check
      deprecated: false
      description: ''
      operationId: healthInvoice
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            type: object
            properties: {}
      security: []
      produces:
        - application/json
      x-google-backend:
        address: "${invoice_url}"
        protocol: h2
        path_translation: APPEND_PATH_TO_ADDRESS
swagger: '2.0'
definitions: {}
securityDefinitions:
  tokenAdmin:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "http://capibaras.io/"
    x-google-jwks_uri: "http://capibaras.io/.well-known/jwks.json"
    x-google-jwt-locations:
    - header: "Authorization"
      value_prefix: "Bearer "
    x-google-audiences: "admin"
x-components: {}
